"$schema" = 'https://starship.rs/config-schema.json'

format = '$directory$os$character'

add_newline = true

[character]
success_symbol = '[➜](bold green)'

[username]
disabled = false
show_always = true

[package]
disabled = true

[os]
format = "[($symbol)]($style)"
style = "bold red"
disabled = false

[shell]
disabled = false
